<?php ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- <title>Page d'Accueuil</title> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

    <div class="container">
        <h1>Liste des albums</h1>
        <table class="table table-striped-columns shadow-sm w-6">
            <thead>
                <th>ID</th>
                <th>Titre</th>
                <th>Artiste</th>
                <th>Date d'ajout</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </thead>
            <tbody>
            <?php foreach($albums as $album) : ?>
                <tr>
                    <td><?= $album['id'] ?></td>
                    <td><?= $album['title'] ?></td>
                    <td><?= $album['artiste'] ?></td>
                    <td><?= $album['create_at'] ?></td>
                    <td><a href="/edit?id=<?php echo $album['id']; ?>"></a></td>
                    <td><a href="/edit?id=<?php echo $album['id']; ?>"></a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <div class="container">
            <h2>Ajouter un nouvel album</h2>
            <form action="/add" method="post">
                <input type="text" class="form-control" name="title" placeholder="Titre de l'album"><br>
                <input type="text" class="form-control" name="artiste" placeholder="Nom de l'artiste"><br>
                <input type="submit" class="btn btn-primary" name="submit" value="Ajouter">
            </form>
        </div>
    </div>
</body>

</html>